src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use function Symfony\Component\String\u;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Product;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="comment.blank")
     * @Assert\Length(
     *     min=5,
     *     minMessage="comment.too_short",
     *     max=255,
     *     maxMessage="comment.too_long"
     * )
     */
    private $content;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @Assert\IsTrue(message="comment.is_spam")
     */
    public function isLegitComment(): bool
    {
        $containsInvalidCharacters = null !== u($this->content)->indexOf('@');

        return !$containsInvalidCharacters;
    }
}

src/Entity/Delivery.php
<?php

namespace App\Entity;

use App\Repository\DeliveryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DeliveryRepository::class)
 */
class Delivery
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $Address;

    /**
     * @ORM\Column(type="integer")
     */
    private $home_number;

    /**
     * @ORM\Column(type="integer")
     */
    private $flat;

    /**
     * @ORM\OneToOne(targetEntity=Order::class, inversedBy="delivery", cascade={"persist", "remove"})
     */
    private $rel_order;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $City;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getHomeNumber(): ?int
    {
        return $this->home_number;
    }

    public function setHomeNumber(int $home_number): self
    {
        $this->home_number = $home_number;

        return $this;
    }

    public function getFlat(): ?int
    {
        return $this->flat;
    }

    public function setFlat(int $flat): self
    {
        $this->flat = $flat;

        return $this;
    }

    public function getRelOrder(): ?Order
    {
        return $this->rel_order;
    }

    public function setRelOrder(?Order $rel_order): self
    {
        $this->rel_order = $rel_order;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('items', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])
            ->add('save', SubmitType::class)
            ->add('clear', SubmitType::class);

        $builder->addEventSubscriber(new RemoveCartItemListener());
        $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Delivery;
use App\Entity\OrderItem;
use App\Entity\User;
use App\Form\CartType;
use App\Form\DeliveryType;
use App\Manager\CartManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * Class CartController
 * @package App\Controller
 */

class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="cart")
     * @param CartManager $cartManager
     * @param Request $request
     * @return Response
     */
    public function index(CartManager $cartManager, Request $request): Response
    {

        $this->denyAccessUnlessGranted('ROLE_USER', null, 'Authorize first!');

        $cart = $cartManager->getCurrentCart();
        $form = $this->createForm(CartType::class, $cart);

        $form->handleRequest($request);
        //$em = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdatedAt(new \DateTime());
            $cartManager->save($cart);
            //foreach ($cart->getItems() as $item) {
            //    $em->persist($item);
            //    $em->flush();
            //  }
            return $this->redirectToRoute('cart');
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route ("/cart/checkout", name="checkout")
     * @param CartManager $cartManager
     * @param Request $request
     * @param SluggerInterface $slugger
     * @return Response
     */
    public function pay(CartManager $cartManager, Request $request, SluggerInterface $slugger): Response
    {


        $cart = $cartManager->getCurrentCart();
        $delivery = new Delivery();

        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->findOneBy(['email' => $this->getUser()->getUsername()]);

        $form = $this->createForm(DeliveryType::class, $delivery);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() && ($cart->getTotal() > 0)) {
            $em = $this->getDoctrine()->getManager();
            $cart->setUpdatedAt(new \DateTime());
            $delivery->setRelOrder($cart);
            $cart->setDelivery($delivery);
            $user->addOrder($cart);
            $cart->setSlug($slugger->slug(date_format($cart->getUpdatedAt(), 'Y-m-d H:i:s') . $user->getUsername()));
            $cart->setStatus('order');
            $cartManager->cartOrdered($cart);
            $em->persist($delivery);
            $em->flush();
            $em->persist($user);
            $em->flush();
            foreach($cart->getItems() as $item){
                $item->getProduct()->setQuantity($item->getProduct()->getQuantity() - $item->getQuantity());
                $em->persist($item);
                $em->flush();
            }
            return $this->redirectToRoute('cart');
        }

        return $this->render('cart/checkout.html.twig', [
            'cart' => $cart,
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }


    /**
     * @Route("/cart/increase/{id}", name="increase_cart_product_process")
     * @param OrderItem $orderItem
     * @return Response
     */

    public function increaseProduct(OrderItem $orderItem)
    {

        $this->denyAccessUnlessGranted('ROLE_USER', null, 'Authorize first!');

        $em = $this->getDoctrine()->getManager();

        if ($orderItem->getQuantity() >= $orderItem->getProduct()->getQuantity()) {
            return $this->redirectToRoute("cart");
        } else {
            $orderItem->setQuantity($orderItem->getQuantity() + 1);
            $em->persist($orderItem);
            $em->flush();

        }

        return $this->redirectToRoute("cart");
    }

    /**
     * @Route("/cart/decrease/{id}", name="decrease_cart_product_process")
     * @param OrderItem $orderItem
     * @return Response
     */
    public function decreaseProduct(OrderItem $orderItem)
    {

        $em = $this->getDoctrine()->getManager();


        if ($orderItem->getQuantity() > 1) {
            $orderItem->setQuantity($orderItem->getQuantity() - 1);
            $em->persist($orderItem);
            $em->flush();

        } else {
            $em->remove($orderItem);
            $em->flush();
        }

        return $this->redirectToRoute("cart");
    }

    /**
     * @Route("/cart/maxAV/{id}", name="set_max_cart_product_process")
     * @param OrderItem $orderItem
     * @return Response
     */
    public function setMaxAvailable(OrderItem $orderItem)
    {

        $em = $this->getDoctrine()->getManager();

        if ($orderItem->getQuantity() >= $orderItem->getProduct()->getQuantity()) {
            $orderItem->setQuantity($orderItem->getProduct()->getQuantity());
            $em->persist($orderItem);
            $em->flush();
        }

        return $this->redirectToRoute("cart");
    }
}

templates/cart/checkout.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <style>

        article {
            background-color: RGB(249, 255, 16); /* Цвет фона под заголовком */
            max-width: 600px;
        }
        input {
            border-radius: 10px;
        }

    </style>

<article class="well" >
<h2>PAYMENT</h2>
    <h5>card number</h5>
    <p><input type="text" size="16" maxlength="16" onkeypress='return event.charCode >= 48 && event.charCode <= 57'></p>
    <h5>expire date</h5>
    <p><input type="date" name="begin"
           placeholder="dd-mm-yyyy" value=""
              min="2018-01-01" max="2030-12-31"></p>
    <h5>cardholder name</h5>
    <p><input type="text" maxlength="20"></p>
    <h5>cardholder surname</h5>
    <p><input type="text" maxlength="20"></p>
</article>

<div class="card bg-light mb-3 mt-5" style="width: 800px">
    <div class="card-body">

    {{ form_start(form) }}
    <h2>Delivery info</h2>
        <div class="form_group">
            <div class="col-md-6 mb-3">
                {{ form_row(form.city, {'attr': {'class':
                    'form-control'}}) }}
            </div>
        </div>
    <div class="form_group">
        <div class="col-md-6 mb-3">
            {{ form_row(form.Address, {'attr': {'class':
                'form-control'}}) }}
        </div>
    </div>
    <div class="form_group">
        <div class="col-md-6 mb-3">
            {{ form_row(form.home_number, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>
    <div class="form_group">
        <div class="col-md-6 mb-3">
            {{ form_row(form.flat, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>
    {% if user.cash > cart.total %}
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3" style="margin-top:5px;">
            <button type="submit" class="btn btn-primary">
                <i class="fa fa-btn fa-handshake-o"></i> Update
            </button>
        </div>
    </div>
        {% else %}

    {% endif %}
    {{ form_end(form) }}

    </div>
</div>

    <a href="{{ path('cart') }}" class="btn btn-primary" type="submit">
        <i class="fa fa-backward" aria-hidden="true"></i> BACK
    </a>
{% endblock %}

{% block title %}

{% endblock %}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart{% endblock %}

{% block body %}
    <style>
    .alert{
        background: #921e12;
    }
    </style>
    <div class="container mt-4">
        <h1>Your Cart</h1>
        {% if cart.items.count > 0 %}
            <div class="row mt-4">
                <!-- List of items -->
                <div class="col-md-8">
                    {{ form_start(form) }}
                    <div class="card">
                        <div class="card-header bg-dark text-white d-flex">
                            <div class="ml-auto">
                                {{ form_widget(form.save, {'attr': {'class': 'btn btn-warning'}}) }}
                                {{ form_widget(form.clear, {'attr': {'class': 'btn btn-light'}}) }}
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for item in form.items %}
                                <li class="list-group-item d-flex">
                                    <div class="flex-fill mr-2">
                                        <img src="https://via.placeholder.com/200x150" width="64" alt="Product image">
                                    </div>
                                    <div class="flex-fill mr-2">
                                        <h5 class="mt-0 mb-0">{{ item.vars.data.product.name }}</h5>
                                        <small>{{ item.vars.data.product.description[:50] }}...</small>
                                        <div class="form-inline mt-2">
                                            <div class="form-group mb-0 mr-2">
                                                <a  href="{{ path('decrease_cart_product_process', {'id':item.vars.data.id}) }}">
                                                    <i class="fa fa-minus-square" aria-hidden="true"></i>
                                                </a>

                                                {{ item.vars.data.quantity }}

                                                <a  href="{{ path('increase_cart_product_process', {'id':item.vars.data.id}) }}">
                                                    <i class="fa fa-plus-square" aria-hidden="true"></i>
                                                </a>
                                            </div>
                                            {{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm'}}) }}
                                        </div>
                                    </div>
                                    <div class="flex-fill mr-2 text-right">
                                        <b>{{ item.vars.data.product.price }} ₽</b>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {{ form_end(form) }}
                </div>

                <div class="col-md-4">
                    <div class="card mt-4 mt-md-0">
                        <h3 class="card-header bg-dark text-white">Summary</h3>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between">
                                <div><b>Total</b></div>
                                <span><b>{{ cart.total }} ₽</b></span>
                            </li>
                        </ul>
                        <div class="card-body">
                            <a href="{{ path('checkout')}}" class="btn btn-warning">Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-info">
                Your cart is empty. Go to the <a href="{{ path('product_index') }}">product list</a>.
            </div>
        {% endif %}
    </div>
{% endblock %}