src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use function Symfony\Component\String\u;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Product;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="comment.blank")
     * @Assert\Length(
     *     min=5,
     *     minMessage="comment.too_short",
     *     max=255,
     *     maxMessage="comment.too_long"
     * )
     */
    private $content;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @Assert\IsTrue(message="comment.is_spam")
     */
    public function isLegitComment(): bool
    {
        $containsInvalidCharacters = null !== u($this->content)->indexOf('@');

        return !$containsInvalidCharacters;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $summary;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime",options={"default"= "CURRENT_TIMESTAMP"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg"}, maxSize="5M")
     */
    private $image_form;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category",inversedBy="product")
     */
    private $category;

    /**
     * @var Tag[]|Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", cascade={"persist"})
     * @ORM\JoinTable(name="symfony_demo_post_tag")
     * @ORM\OrderBy({"name": "ASC"})
     * @Assert\Count(max="4", maxMessage="product.too_many_tags")
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="Product")
     */
    private $comments;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImageForm()
    {
        return $this->image_form;
    }

    /**
     * @param mixed $image_form
     */
    public function setImageForm($image_form)
    {
        $this->image_form = $image_form;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProduct($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getProduct() === $this) {
                $comment->setProduct(null);
            }
        }

        return $this;
    }

}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Form\Type\TagsInputType;

class ProductType extends AbstractType
{
    private $slugger;

    // Form types are services, so you can inject other services in them if needed
    public function __construct(SluggerInterface $slugger)
    {
        $this->slugger = $slugger;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('name',TextType::class)
            ->add('summary',TextType::class)
            ->add('price',MoneyType::class)
            ->add('description',TextareaType::class)
            ->add('summary',TextType::class)
            ->add('image_form', FileType::class, ['required' => true])
            ->add('quantity',IntegerType::class)
            ->add('category',EntityType::class, ['class'=>'App\Entity\Category'])
            ->add('tags', TagsInputType::class, [
                'label' => 'label.tags',
                'required' => false,
            ])
            ->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
                /** @var Product */
                $product = $event->getData();
                if (null !== $ProductTitle = $product->getName()) {
                    $product->setSlug($this->slugger->slug($ProductTitle)->lower());
                }
            })
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\OrderItem;
use App\Entity\Product;
use App\Entity\Comment;
use App\Event\CommentCreatedEvent;
use App\Form\AddToCartType;
use App\Form\CommentType;
use App\Manager\CartManager;
use Knp\Component\Pager\PaginatorInterface;
use App\Repository\ProductRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
@Route("/product")
 */
const MaxPage=10;

class ProductController extends AbstractController
{
    /**
     * @Route("/", defaults={"page": "1", "_format"="html"}, methods="GET", name="product_index")
     * @Route("/page/{page<[1-9]\d*>}", defaults={"_format"="html"}, methods="GET", name="product_index_paginated")
     * @Cache(smaxage="10")
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        $em = $this->getDoctrine()->getManager();

        $ProductRepository = $em->getRepository(Product::class);

        $ProductsQuery=$ProductRepository->createQueryBuilder('p')
            ->where("p.quantity > 0")
            ->getQuery();
        $CategoryRepository=$em->getRepository(Category::class);
        $CategoryQuery=$CategoryRepository->findAll();

        $Products=$paginator->paginate($ProductsQuery,$request->query

            ->getInt('page',1),MaxPage);


        return $this->render('product/index.html.twig', [
            'products' => $Products,
            'categories'=>$CategoryQuery]);
    }

    /**
     * @Route("/product/{slug}", name="product.detail")
     * @param Product $product
     * @param Request $request
     * @param CartManager $cartManager
     * @return Response
     */
    public function detail(Product $product, Request $request, CartManager $cartManager): Response
    {
        $orderItem = new OrderItem();
        $orderItem->setProduct($product);
        $form = $this->createForm(AddToCartType::class, $orderItem);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $item = $form->getData();
            $cart = $cartManager->getCurrentCart();
            $cart
                ->addItem($item)
                ->setUpdatedAt(new \DateTime());

            $cartManager->save($cart);

            return $this->redirectToRoute('product.detail', ['slug' => $product->getSlug()]);
        }

        return $this->render('product/product_show.html.twig', [
            'product' => $product,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/comment/{productSlug}/new", methods="POST", name="comment_new")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @ParamConverter("product", options={"mapping": {"productSlug": "slug"}})
     * @param Request $request
     * @param Product $product
     * @param EventDispatcherInterface $eventDispatcher
     * @return Response
     */
    public function commentNew(Request $request, Product $product, EventDispatcherInterface $eventDispatcher): Response
    {
        $comment = new Comment();
        $comment->setAuthor($this->getUser());
        $product->addComment($comment);

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $comment->setPublishedAt(new \DateTime());
            $em->persist($comment);
            $em->flush();
            $eventDispatcher->dispatch(new CommentCreatedEvent($comment));

            return $this->redirectToRoute('product.detail', ['slug' => $product->getSlug()]);
        }

        return $this->render('product/comment_form_error.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    public function commentForm(Product $product): Response
    {
        $form = $this->createForm(CommentType::class);

        return $this->render('product/_comment_form.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/search", methods="GET", name="product_search")
     * @param Request $request
     * @param ProductRepository $product
     * @return Response
     */
    public function search(Request $request, ProductRepository $product): Response
    {
        $query = $request->query->get('q', '');
        $limit = $request->query->get('l', 10);

        if (!$request->isXmlHttpRequest()) {
            return $this->render('product/search.html.twig', ['query' => $query]);
        }

        $foundProducts = $product->findBySearchQuery($query, $limit);

        $results = [];
        foreach ($foundProducts as $product) {
            $results[] = [
                'title' => htmlspecialchars($product->getName(), ENT_COMPAT | ENT_HTML5),
                'date' => $product->getCreatedAt()->format('M d, Y'),
                'image' => htmlspecialchars($product->getImage(), ENT_COMPAT | ENT_HTML5),
                'summary' => htmlspecialchars($product->getSummary(), ENT_COMPAT | ENT_HTML5),
                'url' => $this->generateUrl('product.detail', ['slug' => $product->getSlug()]),
            ];
        }

        return $this->json($results);
    }


    /**
     * @Route("/search/cat/{id}", methods="GET", name="category_search")
     * @param Request $request
     * @param Category $category
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function catsearch(Request $request, Category $category,PaginatorInterface $paginator): Response
    {
        $em = $this->getDoctrine()->getManager();

        $foundProducts = $category->getProduct();

        $Products=$paginator->paginate($foundProducts,$request->query

            ->getInt('page',1),MaxPage);

        $CategoryRepository=$em->getRepository(Category::class);
        $CategoryQuery=$CategoryRepository->findAll();

        return $this->render('product/index.html.twig', [
            'products' => $Products,'categories'=>$CategoryQuery]);
    }
}

templates/product/_comment_form.html.twig
{{ form_start(form, {method: 'POST', action: path('comment_new', {'productSlug': product.slug})}) }}
    <fieldset>
        <legend>
            <i class="fa fa-comment" aria-hidden="true"></i> Add comment
        </legend>

        {# Render any global form error (e.g. when a constraint on a public getter method failed) #}
        {{ form_errors(form) }}

        <div class="form-group {% if not form.content.vars.valid %}has-error{% endif %}">
            {{ form_label(form.content, 'label.content', {label_attr: {class: 'sr-only'}}) }}

            {# Render any errors for the "content" field (e.g. when a class property constraint failed) #}
            {{ form_errors(form.content) }}

            {{ form_widget(form.content, {attr: {rows: 10}}) }}
        </div>

        <div class="form-group">
            <button class="btn btn-primary pull-right" type="submit">
                <i class="fa fa-paper-plane" aria-hidden="true"></i> Publish
            </button>
        </div>
    </fieldset>
{{ form_end(form) }}

templates/product/_delete_post_confirmation.html.twig
{# Bootstrap modal, see https://getbootstrap.com/docs/3.4/javascript/#modals #}
<div class="modal fade" id="confirmationModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h4>{{ 'delete_post_modal.title'|trans }}</h4>
                <p>{{ 'delete_post_modal.body'|trans }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btnNo" data-dismiss="modal">
                    <i class="fa fa-ban" aria-hidden="true"></i> {{ 'label.cancel'|trans }}
                </button>
                <button type="button" class="btn btn-danger" id="btnYes" data-dismiss="modal">
                    <i class="fa fa-trash" aria-hidden="true"></i> {{ 'label.delete_post'|trans }}
                </button>
            </div>
        </div>
    </div>
</div>

templates/product/_flash_messages.html.twig
{#
   This is a template fragment designed to be included in other templates
   See https://symfony.com/doc/current/templates.html#including-templates

   A common practice to better distinguish between templates and fragments is to
   prefix fragments with an underscore. That's why this template is called
   '_flash_messages.html.twig' instead of 'flash_messages.html.twig'
#}

{#
   The check is needed to prevent starting the session when looking for "flash messages":
   https://symfony.com/doc/current/session.html#avoid-starting-sessions-for-anonymous-users

   TIP: With FOSHttpCache you can also adapt this to make it cache safe:
   https://foshttpcachebundle.readthedocs.io/en/latest/features/helpers/flash-message.html
#}
{% if app.request.hasPreviousSession %}
    <div class="messages">
        {% for type, messages in app.flashes %}
            {% for message in messages %}
                {# Bootstrap alert, see https://getbootstrap.com/docs/3.4/components/#alerts #}
                <div class="alert alert-dismissible alert-{{ type }} fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="{{ 'action.close'|trans }}">
                        <span aria-hidden="true">&times;</span>
                    </button>

                    {{ message|trans }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endif %}

templates/product/_product_tags.html.twig
{% if not product.tags.empty %}
    <p class="post-tags">
        {% for tag in product.tags %}
            <a href="{{ path('product_index', {'tag': tag.name == app.request.query.get('tag') ? null : tag.name}) }}"
               class="label label-{{ tag.name == app.request.query.get('tag') ? 'success' : 'default' }}"
            >
                <i class="fa fa-tag"></i> {{ tag.name }}
            </a>
        {% endfor %}
    </p>
{% endif %}

templates/product/comment_form_error.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'comment_form_error' %}

{% block main %}
    <h1 class="text-danger">{{ 'title.comment_error'|trans }}</h1>

    <div class="well">
        {{ include('blog/_comment_form.html.twig') }}
    </div>
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'blog_index' %}


{% block header %}
    <header>
        <div class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header col-md-3 col-lg-2">
                    <a class="navbar-brand" href="{{ path('product_index') }}">
                        Maybe Website
                    </a>

                    <button type="button" class="navbar-toggle"
                            data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="sr-only">Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">

                        {% block header_navigation_links %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <li>
                                    <a href="{{ path('admin_product_index') }}">
                                        <i class="fa fa-lock" aria-hidden="true"></i> Admin
                                    </a>
                                </li>
                            {% endif %}
                        {% endblock %}


                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false" id="categories">
                                <i class="fa fa-bars" aria-hidden="true"></i>Categories
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu user" role="menu" aria-labelledby="categories">
                            {% for category in categories %}
                        <li>
                            <a href="{{ path('category_search', {id: category.id}) }}">
                                <i class="fa fa-cart"></i>{{ category.name }}
                            </a>
                        </li>
                        {% endfor %}
                            </ul>>
                        </li>

                        <li>
                            <a href="{{ path('product_search') }}"> <i class="fa fa-search"></i> Search</a>
                        </li>

                        <li>
                            <a href="{{ path('cart') }}"> <i class="fa fa-shopping-cart"></i> Cart</a>
                        </li>

                        {% if app.user %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-expanded="false" id="user">
                                    <i class="fa fa-user" aria-hidden="true"></i>{{ app.user.username }}
                                    <span class="caret"></span>
                                    <span class="sr-only">{{ app.user.email }}</span>
                                </a>
                                <ul class="dropdown-menu user" role="menu" aria-labelledby="user">
                                    <li>
                                        <a href="{{ path('user_edit') }}">
                                            <i class="fa fa-edit" aria-hidden="true"></i> User
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href={{ path('orderlist') }}>
                                            <i class="fa fa-archive" aria-hidden="true"></i> Orders
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="{{ path('app_logout') }}">
                                            <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        {% else %}
                            <li>
                                <a href="{{ path('app_login') }}">
                                    <i class="fa fa-sign-in " aria-hidden="true"></i> Login
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
    {% for product in products %}
        <article class="well">
            <h2>
                <td><img src="/public/uploads/brochures/{{ product.image }}" style="width: 100px;"></td>
                <a href="{{ path('product.detail', {slug: product.slug}) }}">
                    {{ product.name }}
                </a>
                <br>
                <i class="fa fa-money" aria-hidden="true">
                    {{ product.price }}₽
                </i>
            </h2>

            <p>{{ product.summary }}</p>
            {{ include('product/_product_tags.html.twig') }}
        </article>
    {% else %}
        <div class="well">no products found</div>
    {% endfor %}

    <div class="navigation text-center">
        {{ knp_pagination_render(products) }}
    </div>
{% endblock %}

templates/product/product_show.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'blog_post_show' %}

{% block main %}
<article class="well">
    <td><img src="https://via.placeholder.com/250x250"style="width: 250px;margin-right: 50%">
            {{ product.price }}₽
        </a>
    </td>

        <h1>{{ product.name }}</h1>

        {{ include('product/_product_tags.html.twig') }}

    {{ form_start(form, {'attr': {'class': 'mt-4 p-4 bg-light'}}) }}
    <div class="row mt-4">
        {{ form_label(form.quantity) }}
        {{ form_widget(form.quantity, {
            'attr': {
                'class': 'form-control ' ~ (form.quantity.vars.valid ? '' : 'is-invalid')
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.quantity) }}
        </div>
    </div>
    {{ form_widget(form.add, {'attr': {'class': 'btn btn-warning w-25'}}) }}
    {{ form_end(form) }}

</article>
    <article class="well">
        <h3>Description</h3>
    <i class="fa fa-info">
        {{ product.description|markdown_to_html}}
    </i>

</article>



    <div id="post-add-comment" class="well">
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            {{ render(controller('App\\Controller\\ProductController::commentForm', {'id': product.id})) }}
        {% else %}
            <p>
                <a class="btn btn-success" href="{{ path('app_login', {'redirect_to': app.request.pathInfo}) }}">
                    <i class="fa fa-sign-in" aria-hidden="true"></i> Login
                </a>
                only authorized users can publish comments
            </p>
        {% endif %}
    </div>

    <h3>
        <i class="fa fa-comments" aria-hidden="true"></i>  amount of comments {{product.comments|length}}
    </h3>

    {% for comment in product.comments %}
        <div class="row post-comment">
            <a name="comment_{{ comment.id }}"></a>
            <h4 class="col-sm-3">
                <strong>{{ comment.author.username }}</strong>
                <strong>{{ comment.publishedAt|format_datetime('medium', 'short', '', 'UTC') }}</strong>
            </h4>
            <div class="col-sm-9">
                {{ comment.content|markdown_to_html}}
            </div>
        </div>
    {% else %}
        <div class="post-comment">
            <p>no comments yet</p>
        </div>
    {% endfor %}
{% endblock %}

{% block sidebar %}

{% endblock %}

templates/product/search.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('search') }}
{% endblock %}

{% block body_id 'blog_search' %}

{% block main %}
    <form action="{{ path('product_search') }}" method="get">
        <div class="form-group">
            <input name="q"
                   class="form-control search-field"
                   placeholder="Enter searching product"
                   autocomplete="off"
                   value="{{ query }}"
                   autofocus
                   data-no-results-message="unable to find anything related">
        </div>
    </form>

    <div id="results">
    </div>
{% endblock %}

{% block sidebar %}
{% endblock %}