src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity=OrderItem::class, mappedBy="orderRef", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $items;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status = self::STATUS_CART;

    /**
     * An order that is in progress, not placed yet.
     *
     * @var string
     */
    const STATUS_CART = 'cart';

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     */
    private $User;

    /**
     * @ORM\OneToOne(targetEntity=Delivery::class, mappedBy="rel_order", cascade={"persist", "remove"})
     */
    private $delivery;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(OrderItem $item): self
    {
        foreach ($this->getItems() as $existingItem) {
            // The item already exists, update the quantity
            if ($existingItem->equals($item)) {
                $existingItem->setQuantity(
                    $existingItem->getQuantity() + $item->getQuantity()
                );
                return $this;
            }
        }

        $this->items[] = $item;
        $item->setOrderRef($this);

        return $this;
    }



    public function removeItem(OrderItem $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getOrderRef() === $this) {
                $item->setOrderRef(null);
            }
        }

        return $this;
    }


    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Removes all items from the order.
     *
     * @return $this
     */
    public function removeItems(): self
    {
        foreach ($this->getItems() as $item) {
            $this->removeItem($item);
        }

        return $this;
    }

    /**
     * Calculates the order total.
     *
     * @return float
     */
    public function getTotal(): float
    {
        $total = 0;

        foreach ($this->getItems() as $item) {
            $total += $item->getTotal();
        }

        return $total;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDelivery(): ?Delivery
    {
        return $this->delivery;
    }

    public function setDelivery(?Delivery $delivery): self
    {
        // unset the owning side of the relation if necessary
        if ($delivery === null && $this->delivery !== null) {
            $this->delivery->setRelOrder(null);
        }

        // set the owning side of the relation if necessary
        if ($delivery !== null && $delivery->getRelOrder() !== $this) {
            $delivery->setRelOrder($this);
        }

        $this->delivery = $delivery;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %}Shopping website{% endblock %}</title>
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
</head>

<body id="{% block body_id %}{% endblock %}">

{% block header %}
    <header>
        <div class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header col-md-3 col-lg-2">
                    <a class="navbar-brand" href="{{ path('product_index') }}">
                        Maybe Website
                    </a>

                    <button type="button" class="navbar-toggle"
                            data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="sr-only">Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">

                        {% block header_navigation_links %}
                            <li>
                                <a href="{{ path('product_index') }}">
                                    <i class="fa fa-home" aria-hidden="true"></i> Menu
                                </a>
                            </li>

                            {% if is_granted('ROLE_ADMIN') %}
                                <li>
                                    <a href="{{ path('admin_product_index') }}">
                                        <i class="fa fa-lock" aria-hidden="true"></i> Admin
                                    </a>
                                </li>
                            {% endif %}
                        {% endblock %}

                        <li>
                            <a href="{{ path('product_search') }}"> <i class="fa fa-search"></i> Search</a>
                        </li>

                        <li>
                            <a href="{{ path('cart') }}"> <i class="fa fa-shopping-cart"></i> Cart</a>
                        </li>


                        {% if app.user %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="user">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                    <span class="caret"></span>
                                    <span class="sr-only">{{ app.user.email }}</span>
                                </a>
                                <ul class="dropdown-menu user" role="menu" aria-labelledby="user">
                                    <li>
                                        <a href="{{ path('user_edit') }}">
                                            <i class="fa fa-edit" aria-hidden="true"></i> User
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                     <li>
                                        <a href={{ path('orderlist') }}>
                                            <i class="fa fa-archive" aria-hidden="true"></i> Orders
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="{{ path('app_logout') }}">
                                            <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            {% else %}
                                <li>
                                    <a href="{{ path('app_login') }}">
                                        <i class="fa fa-sign-in " aria-hidden="true"></i> Login
                                    </a>
                                </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

<div class="container body-container">
    {% block body %}
        <div class="row">
            <div id="main" class="col-sm-9">
                {{ include('product/_flash_messages.html.twig') }}

                {% block main %}{% endblock %}
            </div>

            <div id="sidebar" class="col-sm-3">
                {% block sidebar %}
                {% endblock %}
            </div>
        </div>
    {% endblock %}
</div>

{% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div id="footer-copyright" class="col-md-6">
                    <p>&copy; {{ 'now'|date('Y') }} - The Symfony Project</p>
                    <p>{{ 'mit_license'|trans }}</p>
                </div>
                <div id="footer-resources" class="col-md-6">
                    <a href="https://symfony.com/blog/" title="Symfony Blog">
                        <i class="fa fa-rss" aria-hidden="true"></i>
                    </a>
                    <a href="#" title="Github link">
                        <i class="fa fa-github" aria-hidden="true"></i>
                    </a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}
</body>
</html>